info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: A web service that, upon request, collects data from the public API
    of the national bank and saves the data to the local TEST database
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger kursRates API
  version: "0.1"
paths:
  /currency/save/{date}:
    post:
      consumes:
      - application/json
      description: Save currency data for a specific date.
      parameters:
      - description: Date in DD.MM.YYYY format
        in: path
        name: date
        required: true
        type: string
      responses: {}
      summary: Save currency data
      tags:
      - currency
swagger: "2.0"
